export const SOURCEOG_ERROR_CODES = {
  CONFIG_INVALID: "SOURCEOG_CONFIG_INVALID",
  MANIFEST_INVALID: "SOURCEOG_MANIFEST_INVALID",
  ROUTE_NOT_FOUND: "SOURCEOG_ROUTE_NOT_FOUND",
  ROUTE_CONFLICT: "SOURCEOG_ROUTE_CONFLICT",
  METHOD_NOT_ALLOWED: "SOURCEOG_METHOD_NOT_ALLOWED",
  RUNTIME_INCOMPATIBLE: "SOURCEOG_RUNTIME_INCOMPATIBLE",
  ADAPTER_CAPABILITY_MISSING: "SOURCEOG_ADAPTER_CAPABILITY_MISSING",
  ADAPTER_PARITY_FAILED: "SOURCEOG_ADAPTER_PARITY_FAILED",
  BUNDLE_BUDGET_EXCEEDED: "SOURCEOG_BUNDLE_BUDGET_EXCEEDED",
  MODULE_BOUNDARY_VIOLATION: "SOURCEOG_MODULE_BOUNDARY_VIOLATION",
  ACTION_NOT_FOUND: "SOURCEOG_ACTION_NOT_FOUND",
  ACTION_EXECUTION_FAILED: "SOURCEOG_ACTION_EXECUTION_FAILED",
  RENDER_FAILED: "SOURCEOG_RENDER_FAILED",
  REDIRECT_INTERRUPT: "SOURCEOG_REDIRECT_INTERRUPT",
  NOT_FOUND_INTERRUPT: "SOURCEOG_NOT_FOUND_INTERRUPT",
  SECURITY_POLICY_VIOLATION: "SOURCEOG_SECURITY_POLICY_VIOLATION",
  AUTOMATION_INVALID: "SOURCEOG_AUTOMATION_INVALID",
  EDGE_CAPABILITY_VIOLATION: "EDGE_CAPABILITY_VIOLATION"
} as const;

export type SourceOGErrorCode = (typeof SOURCEOG_ERROR_CODES)[keyof typeof SOURCEOG_ERROR_CODES];

export class SourceOGError extends Error {
  public readonly code: SourceOGErrorCode;

  public readonly details?: Record<string, unknown>;

  public constructor(code: SourceOGErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.code = code;
    this.details = details;
    this.name = "SourceOGError";
  }
}
