export declare const SOURCEOG_ERROR_CODES: {
    readonly CONFIG_INVALID: "SOURCEOG_CONFIG_INVALID";
    readonly MANIFEST_INVALID: "SOURCEOG_MANIFEST_INVALID";
    readonly ROUTE_NOT_FOUND: "SOURCEOG_ROUTE_NOT_FOUND";
    readonly ROUTE_CONFLICT: "SOURCEOG_ROUTE_CONFLICT";
    readonly METHOD_NOT_ALLOWED: "SOURCEOG_METHOD_NOT_ALLOWED";
    readonly RUNTIME_INCOMPATIBLE: "SOURCEOG_RUNTIME_INCOMPATIBLE";
    readonly ADAPTER_CAPABILITY_MISSING: "SOURCEOG_ADAPTER_CAPABILITY_MISSING";
    readonly ADAPTER_PARITY_FAILED: "SOURCEOG_ADAPTER_PARITY_FAILED";
    readonly BUNDLE_BUDGET_EXCEEDED: "SOURCEOG_BUNDLE_BUDGET_EXCEEDED";
    readonly MODULE_BOUNDARY_VIOLATION: "SOURCEOG_MODULE_BOUNDARY_VIOLATION";
    readonly ACTION_NOT_FOUND: "SOURCEOG_ACTION_NOT_FOUND";
    readonly ACTION_EXECUTION_FAILED: "SOURCEOG_ACTION_EXECUTION_FAILED";
    readonly RENDER_FAILED: "SOURCEOG_RENDER_FAILED";
    readonly REDIRECT_INTERRUPT: "SOURCEOG_REDIRECT_INTERRUPT";
    readonly NOT_FOUND_INTERRUPT: "SOURCEOG_NOT_FOUND_INTERRUPT";
    readonly SECURITY_POLICY_VIOLATION: "SOURCEOG_SECURITY_POLICY_VIOLATION";
    readonly AUTOMATION_INVALID: "SOURCEOG_AUTOMATION_INVALID";
    readonly EDGE_CAPABILITY_VIOLATION: "EDGE_CAPABILITY_VIOLATION";
};
export type SourceOGErrorCode = (typeof SOURCEOG_ERROR_CODES)[keyof typeof SOURCEOG_ERROR_CODES];
export declare class SourceOGError extends Error {
    readonly code: SourceOGErrorCode;
    readonly details?: Record<string, unknown>;
    constructor(code: SourceOGErrorCode, message: string, details?: Record<string, unknown>);
}
